enable safari extension
ShadowmapTechnologies/LocationBrowserPlugin pull request #3
Opened 2022-03-02 10:06 UTC by ahmedsafadii

To test the extension:

- Run `Shadowmap Location.xcodeproj`
- Make sure you select your target (Mac, iOS), it support all platforms
<img width="239" alt="Screen Shot 2022-03-02 at 12 58 56 PM" src="https://user-images.githubusercontent.com/6974081/156339264-9234234d-43ad-4e6e-9da5-7a3661bf83b2.png">
- Click Run
- You would say something like that
<img width="425" alt="Screen Shot 2022-03-02 at 1 02 41 PM" src="https://user-images.githubusercontent.com/6974081/156339982-d71124a6-e4f6-416b-9595-8c9dc5f781ef.png">

- Click open Safari Extention and enable it by doing the checkmark.

<img width="796" alt="Screen Shot 2022-03-02 at 1 03 58 PM" src="https://user-images.githubusercontent.com/6974081/156340207-5dcafe11-1212-4cac-ac83-a21b56e14cff.png">

- Now for Debugging you can from the Developer Menu.
<img width="656" alt="Screen Shot 2022-03-02 at 1 05 00 PM" src="https://user-images.githubusercontent.com/6974081/156340364-5a823d5e-8110-483a-9e74-9e4a36d7ff3d.png">

2022-03-02 10:08 UTC, ahmedsafadii commented
@simonmulser make sure to change the icons, cuz it looks not good atm since I take it from chrome extension.

2022-03-02 10:09 UTC, simonmulser commented
> @simonmulser make sure to change the icons, cuz it looks not good atm since I take it from chrome extension.

Did you found somewhere the resolution needed for the image?

2022-03-02 10:14 UTC, simonmulser commented
What kind of monster is this PR? :D

2022-03-02 10:18 UTC, ahmedsafadii commented
@simonmulser, i didn't do anything just create new project lol, I even remove a lot of useless files which using popup but since you use the action so yeah, the only thing that need to be changes the icons and some of text if you want, for the icon size I already put the icon-{size} so you can replace it, or maybe if you want me to do it for you, just send me your logo with high quality 1024x1024 and I will change it for all icons :)

2022-03-02 10:22 UTC, simonmulser commented
![shadowmap-logo](https://user-images.githubusercontent.com/2686617/156343005-840e3acf-5330-49f0-9578-1c66d3e00b09.png)

Yes, please exchange the pictures! Remember if there is a 2x or 3x you need to use the double or triple resolution. Eg. 20x20@2x you need to use an image which is 40x40 and save it under the filename `iphone-icon-20@2x.png`.

2022-03-02 10:35 UTC, simonmulser commented
Steps:
- Open `Shadowmap Location/safari` in XCode
- Select `Shadowmap Location (macOS) > My Mac (Rosetta)`
- Run
- Opens 
<img width="430" alt="image" src="https://user-images.githubusercontent.com/2686617/156345073-76bdbfc0-5180-4751-9450-b1ead4d83e1e.png">
- Click on `Quit and Open Safari Extension Preferences...`
- Nothing happens


Log:
```
2022-03-02 11:33:22.553868+0100 Shadowmap Location[97188:12705287] Metal API Validation Enabled
```

2022-03-02 10:36 UTC, simonmulser commented
Similar if I run it as `Shadowmap Location (macOS) > My Mac (Rosetta)`. There the log looks as follows:
```
2022-03-02 11:35:23.083698+0100 Shadowmap Location[97300:12707703] Metal API Validation Enabled
2022-03-02 11:35:23.094649+0100 Shadowmap Location[97300:12707703] Errors found! Invalidating cache...
```

2022-03-02 10:45 UTC, simonmulser commented
<img width="262" alt="image" src="https://user-images.githubusercontent.com/2686617/156346871-bbb89cb5-39a2-46a9-b24b-4c256a9f2e39.png">

Please simply use the logo and don't use the grey rectangle in the background.

2022-03-02 10:54 UTC, simonmulser commented
@ahmedsafadii I think it makes sense to rename it to "Shadowmap for Safari" (I see this naming a lot on the App Store) and target it only for MacOS. IMHO it doesn't make sense to have this plugin for iOS. What do you think?

2022-03-02 11:46 UTC, ahmedsafadii commented
> @ahmedsafadii I think it makes sense target it only for MacOS. IMHO it doesn't make sense to have this plugin for iOS. What do you think?

You can simply ignore it and build it only for macOS, and you need to know that the power of Safari Web Extention, you code one and its release for all types, in case you want it for macOS we can just build for macOS.

2022-03-02 11:47 UTC, ahmedsafadii commented
> 

Can you please send me the logo here?

2022-03-02 11:47 UTC, ahmedsafadii commented
> Steps:
> 
> * Open `Shadowmap Location/safari` in XCode
> * Select `Shadowmap Location (macOS) > My Mac (Rosetta)`
> * Run
> * Opens
> 
> <img alt="image" width="430" src="https://user-images.githubusercontent.com/2686617/156345073-76bdbfc0-5180-4751-9450-b1ead4d83e1e.png">
> 
> - Click on `Quit and Open Safari Extension Preferences...` - Nothing happens
> Log:
> 
> ```
> 2022-03-02 11:33:22.553868+0100 Shadowmap Location[97188:12705287] Metal API Validation Enabled
> ```

You need to go to safari browser and then from the preference select extension, you will find it there.

btw we can set a meeting now to run it for you if you want.

2022-03-02 12:41 UTC, simonmulser commented
> > Steps:
> > 
> > * Open `Shadowmap Location/safari` in XCode
> > * Select `Shadowmap Location (macOS) > My Mac (Rosetta)`
> > * Run
> > * Opens
> > 
> > <img alt="image" width="430" src="https://user-images.githubusercontent.com/2686617/156345073-76bdbfc0-5180-4751-9450-b1ead4d83e1e.png">
> > 
> > * Click on `Quit and Open Safari Extension Preferences...` - Nothing happens
> >   Log:
> > 
> > ```
> > 2022-03-02 11:33:22.553868+0100 Shadowmap Location[97188:12705287] Metal API Validation Enabled
> > ```
> 
> You need to go to safari browser and then from the preference select extension, you will find it there.
> 
> btw we can set a meeting now to run it for you if you want.

I saw that. But the button `Quit and Open Safari Extension Preferences...` should work, right? It doesn't work for me. When I click on the button nothing happens.

2022-03-02 13:14 UTC, ahmedsafadii commented
> > > Steps:
> > > 
> > > * Open `Shadowmap Location/safari` in XCode
> > > * Select `Shadowmap Location (macOS) > My Mac (Rosetta)`
> > > * Run
> > > * Opens
> > > 
> > > <img alt="image" width="430" src="https://user-images.githubusercontent.com/2686617/156345073-76bdbfc0-5180-4751-9450-b1ead4d83e1e.png">
> > > 
> > > * Click on `Quit and Open Safari Extension Preferences...` - Nothing happens
> > >   Log:
> > > 
> > > ```
> > > 2022-03-02 11:33:22.553868+0100 Shadowmap Location[97188:12705287] Metal API Validation Enabled
> > > ```
> > 
> > 
> > You need to go to safari browser and then from the preference select extension, you will find it there.
> > btw we can set a meeting now to run it for you if you want.
> 
> I saw that. But the button `Quit and Open Safari Extension Preferences...` should work, right? It doesn't work for me. When I click on the button nothing happens.

If the Extensions preferences window doesn't open automatically, go to the Safari menu and select Preferences. In the preferences window, click on Extensions. The Extensions preference tab opens.

2022-03-02 13:18 UTC, simonmulser commented
> > > > Steps:
> > > > 
> > > > * Open `Shadowmap Location/safari` in XCode
> > > > * Select `Shadowmap Location (macOS) > My Mac (Rosetta)`
> > > > * Run
> > > > * Opens
> > > > 
> > > > <img alt="image" width="430" src="https://user-images.githubusercontent.com/2686617/156345073-76bdbfc0-5180-4751-9450-b1ead4d83e1e.png">
> > > > 
> > > > * Click on `Quit and Open Safari Extension Preferences...` - Nothing happens
> > > >   Log:
> > > > 
> > > > ```
> > > > 2022-03-02 11:33:22.553868+0100 Shadowmap Location[97188:12705287] Metal API Validation Enabled
> > > > ```
> > > 
> > > 
> > > You need to go to safari browser and then from the preference select extension, you will find it there.
> > > btw we can set a meeting now to run it for you if you want.
> > 
> > 
> > I saw that. But the button `Quit and Open Safari Extension Preferences...` should work, right? It doesn't work for me. When I click on the button nothing happens.
> 
> If the Extensions preferences window doesn't open automatically, go to the Safari menu and select Preferences. In the preferences window, click on Extensions. The Extensions preference tab opens.

Yes, I do understand that. Maybe let's discuss the details in a meeting.

Let me know here when you updated the logos!

2022-03-02 13:40 UTC, ahmedsafadii commented
@simonmulser Done, i update all icons, i had to do it using sketch :D

2022-03-02 14:15 UTC, simonmulser requested changes

2022-03-02 14:15 UTC, simonmulser commented on safari/Shared (Extension)/Resources/_locales/en/messages.json
> +        "message": "The Sun is a prerequisite for life on Earth and Shadowmap is the tool to understand it.",
Open the current location from Google Maps/Earth in Shadowmap and vice versa.

2022-03-02 14:15 UTC, simonmulser commented on safari/Shared (Extension)/Resources/_locales/en/messages.json
> +        "description": "Visualize sunlight and shadow anywhere on Earth"
Shadowmap Location is an extension that allows you to open the current location in Shadowmap with one click in Google Maps. The whole thing also works in the other direction. With a click on the extension icon you can display the current location opened in Google Maps/Earth in Shadowmap.

2022-03-02 14:15 UTC, simonmulser commented on safari/Shared (Extension)/Resources/_locales/en/messages.json
> +        "description": "Visualize sunlight and shadow anywhere on Earth"
Shadowmap Location allows you to open the current location from Google Maps/Earth in Shadowmap and vice versa.

2022-03-02 14:17 UTC, simonmulser commented
<img width="709" alt="image" src="https://user-images.githubusercontent.com/2686617/156378771-edb10e44-6c2f-4dc4-b412-21bef8014d3d.png">

Can you check if you can simplify the required rights? Currently it says that the plugin can read any information of the website including passwords, browser history. But maybe this is already the least permissive setting.

2022-03-02 14:18 UTC, simonmulser commented
> @simonmulser Done, i update all icons, i had to do it using sketch :D

Logos are great!

2022-03-02 14:23 UTC, simonmulser commented
Minor and maybe hard to fix: Browser extension icon should be always yellow or yellow when the domain is Google Maps/Earth or Shadowmap. Currently it's only yellow on the tab where it was clicked which is a bit weird.

2022-03-02 14:33 UTC, ahmedsafadii commented
> rights

Sad this alert for all types of plugins only on safari :D
<img width="816" alt="Screen Shot 2022-03-02 at 5 33 45 PM" src="https://user-images.githubusercontent.com/6974081/156382002-a92c9dd7-ad3d-4b95-a815-0cf80578f8af.png">

2022-03-02 14:37 UTC, simonmulser commented
> > rights
> 
> Sad this alert for all types of plugins only on safari :D <img alt="Screen Shot 2022-03-02 at 5 33 45 PM" width="816" src="https://user-images.githubusercontent.com/6974081/156382002-a92c9dd7-ad3d-4b95-a815-0cf80578f8af.png">

Maybe we can restrict the extension only be active on certain domains (Google Maps/Earth and Shadowmap)? But yeah, if there isn't any other option, let's go for this!

2022-03-02 14:41 UTC, ahmedsafadii commented
> > > rights
> > 
> > 
> > Sad this alert for all types of plugins only on safari :D <img alt="Screen Shot 2022-03-02 at 5 33 45 PM" width="816" src="https://user-images.githubusercontent.com/6974081/156382002-a92c9dd7-ad3d-4b95-a815-0cf80578f8af.png">
> 
> Maybe we can restrict the extension only be active on certain domains (Google Maps/Earth and Shadowmap)? But yeah, if there isn't any other option, let's go for this!

https://lapcatsoftware.com/articles/security-safari-extensions.html

```
"permissions": ["activeTab"],
```
This is what we only use we have full permit over correct active tab, but this is normal don't worry.

2022-03-02 15:01 UTC, ahmedsafadii commented
> Minor and maybe hard to fix: Browser extension icon should be always yellow or yellow when the domain is Google Maps/Earth or Shadowmap. Currently, it's only yellow on the tab where it was clicked which is a bit weird.

Nah it's something related to memory inactive and active, so the user clicks on it when needs to be loaded in the activeTab.

and maybe because we are in dev mode, but I read that they are inactive the extnetion if it is not needed and the user shall click on it so he understands that it's working.

2022-03-02 15:03 UTC, simonmulser commented
> > > > rights
> > > 
> > > 
> > > Sad this alert for all types of plugins only on safari :D <img alt="Screen Shot 2022-03-02 at 5 33 45 PM" width="816" src="https://user-images.githubusercontent.com/6974081/156382002-a92c9dd7-ad3d-4b95-a815-0cf80578f8af.png">
> > 
> > 
> > Maybe we can restrict the extension only be active on certain domains (Google Maps/Earth and Shadowmap)? But yeah, if there isn't any other option, let's go for this!
> 
> https://lapcatsoftware.com/articles/security-safari-extensions.html
> 
> ```
> "permissions": ["activeTab"],
> ```
> 
> This is what we only use we have full permit over correct active tab, but this is normal don't worry.

An option we could try would be using the permission `tabs` (https://developer.chrome.com/docs/extensions/reference/tabs/) instead of `activeTab` and then just read the URL from the tab (https://developer.chrome.com/docs/extensions/reference/tabs/#get-the-current-tab).

But yeah, let's leave it as it is!

2022-03-02 15:45 UTC, ahmedsafadii commented
> An option we could try would be using the permission `tabs` (https://developer.chrome.com/docs/extensions/reference/tabs/) instead of `activeTab` and then just read the URL from the tab (https://developer.chrome.com/docs/extensions/reference/tabs/#get-the-current-tab).

I even try that and guess what 

<img width="776" alt="Screen Shot 2022-03-02 at 6 45 46 PM" src="https://user-images.githubusercontent.com/6974081/156396299-f0f931bb-2fba-4c04-92e3-b4a8e4d40eff.png">

same message.

2022-03-02 15:49 UTC, simonmulser commented
> > An option we could try would be using the permission `tabs` (https://developer.chrome.com/docs/extensions/reference/tabs/) instead of `activeTab` and then just read the URL from the tab (https://developer.chrome.com/docs/extensions/reference/tabs/#get-the-current-tab).
> 
> I even try that and guess what
> 
> <img alt="Screen Shot 2022-03-02 at 6 45 46 PM" width="776" src="https://user-images.githubusercontent.com/6974081/156396299-f0f931bb-2fba-4c04-92e3-b4a8e4d40eff.png">
> 
> same message.

This is not the same message Ahmed. This message is way better! It doesn't say anything about sensitive information like passwords and credit cards.

So if we can work with this permissions would be better IMHO. Or am I missing something?

2022-03-02 15:56 UTC, ahmedsafadii commented
> > > An option we could try would be using the permission `tabs` (https://developer.chrome.com/docs/extensions/reference/tabs/) instead of `activeTab` and then just read the URL from the tab (https://developer.chrome.com/docs/extensions/reference/tabs/#get-the-current-tab).
> > 
> > 
> > I even try that and guess what
> > <img alt="Screen Shot 2022-03-02 at 6 45 46 PM" width="776" src="https://user-images.githubusercontent.com/6974081/156396299-f0f931bb-2fba-4c04-92e3-b4a8e4d40eff.png">
> > same message.
> 
> This is not the same message Ahmed. This message is way better! It doesn't say anything about sensitive information like passwords and credit cards.
> 
> So if we can work with this permissions would be better IMHO. Or am I missing something?

OHHHH yes sorry mb, I had read the above extension message, wait then let me try to get the tab URL from tabs and see.

2022-03-02 16:00 UTC, ahmedsafadii commented
<img width="303" alt="Screen Shot 2022-03-02 at 6 59 16 PM" src="https://user-images.githubusercontent.com/6974081/156399207-0e1956a8-bf48-4058-965f-a9959986d22d.png">

are you ok with this ?

2022-03-02 16:03 UTC, simonmulser commented
> <img alt="Screen Shot 2022-03-02 at 6 59 16 PM" width="303" src="https://user-images.githubusercontent.com/6974081/156399207-0e1956a8-bf48-4058-965f-a9959986d22d.png">
> 
> are you ok with this ?

No, that isn't better. Why does it suddenly show "sensitive information, including ...". We just want to read the URL in the tab and we don't wan't to read the content of the website.

So then let's stick with the initial permission. I think this is even worse.

2022-03-03 10:38 UTC, ahmedsafadii commented
@simonmulser zoom?

2022-03-03 13:19 UTC, simonmulser approved these changes

2022-03-03 13:20 UTC, merged